"""외부 Evidence와 내부 판단 산출물 저장소 계약."""

from __future__ import annotations

from typing import Protocol, runtime_checkable

from app.schemas.frozen import (
    Claim,
    ClaimEvaluation,
    ClaimEvidence,
    Evidence,
    EvidenceQueryLink,
    Finding,
    Query,
)


@runtime_checkable
class EvidenceStore(Protocol):
    async def put_queries(self, run_id: str, queries: list[Query]) -> list[str]: ...

    async def get_queries(self, query_ids: list[str]) -> list[Query]: ...

    async def put_many(self, run_id: str, evs: list[Evidence]) -> list[str]: ...

    async def get_many(self, ids: list[str]) -> list[Evidence]: ...

    async def find_by_sha256(self, run_id: str, hashes: list[str]) -> dict[str, str]: ...

    async def link(self, pairs: list[EvidenceQueryLink]) -> None: ...

    async def evidence_ids_for_claim(self, claim_id: str) -> list[str]: ...

    async def evidence_ids_for_queries(self, query_ids: list[str]) -> list[str]: ...


@runtime_checkable
class ReviewStore(Protocol):
    async def put_input(self, run_id: str, body: dict) -> str: ...

    async def get_input(self, input_id: str) -> dict: ...

    async def put_claims(self, run_id: str, items: list[Claim]) -> list[str]: ...

    async def get_claims(self, claim_ids: list[str]) -> list[Claim]: ...

    async def put_claim_evidence(
        self, run_id: str, items: list[ClaimEvidence]
    ) -> list[str]: ...

    async def get_claim_evidence(self, run_id: str, claim_id: str) -> list[ClaimEvidence]: ...

    async def put_claim_evaluations(
        self, run_id: str, items: list[ClaimEvaluation]
    ) -> list[str]: ...

    async def get_claim_evaluations(self, ids: list[str]) -> list[ClaimEvaluation]: ...

    async def put_findings(self, run_id: str, items: list[Finding]) -> list[str]: ...

    async def get_findings(self, ids: list[str]) -> list[Finding]: ...

    async def put_report(self, run_id: str, body: dict) -> str: ...

    async def get_report(self, report_id: str) -> dict | None: ...
